name: Markdown lint (project files)

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.md'
      - 'rfcs/**/*.md'
      - .github/workflows/markdown-lint.yml


jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
  <<<<<<< master
      - uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
  =======
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
  >>>>>>> bfregist
        with:
          node-version: "12"

      - name: Lint markdown files
        run: |
          npx markdownlint-cli '*.md' -i LICENSE.md -i CODE_OF_CONDUCT.md
